# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Bio
    url: /bio/
    weight: 20
  - name: Teaching
    url: /teaching/
    weight: 30
  - name: Projects
    url: /projects/
    weight: 40
  - name: Resume
    url: /resume/
    weight: 50
  - name: Contact
    url: /contact/
    weight: 60
