baseURL: "https://www.andrew.cmu.edu/user/sobla/"
title: Shashank Obla
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Bio
      url: /bio/
      weight: 1
    - name: Teaching
      url: /teaching/
      weight: 2
    - name: Publications
      url: /publications/
      weight: 3
    - name: Projects
      url: /projects/
      weight: 4
    - name: Service
      url: /service/
      weight: 5

params:
  description: "Webpage of Shashank Obla, PhD Candidate in Electrical and Computer Engineering at Carnegie Mellon University."
  author: Shashank Obla
  hideAuthor: true
  googleAnalyticsID: "G-YYCNHNENMQ"
  analytics:
    google:
      SiteVerificationTag: "Zxx7g4bodyxLNUqWQSsSYNcV11JPb0HWst-X9km2Lzs"
  DateFormat: "January 2006"
  defaultTheme: dark
  hideFooter: false
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["bio", "teaching", "publications", "projects", "service"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: false
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true

  profileMode:
    enabled: true
    title: Shashank Obla

    imageUrl: "picture.jpeg"
    imageWidth: 160
    imageHeight: 160
    imageTitle: Shashank Obla
    buttons:
      - name: Bio
        url: /bio/
      - name: Teaching
        url: /teaching/
      - name: Publications
        url: /publications/
      - name: Projects
        url: /projects/
      - name: Service
        url: /service/

  socialIcons:
    - name: Email
      url: "mailto:sobla@andrew.cmu.edu"
    - name: GitHub
      url: "https://github.com/ShashankOV"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/shashankov"

  assets:
    favicon: rayquaza.png
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Shashank Obla"
    icon: rayquaza.png
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - - '$$'
              - '$$'
            - - '\['
              - '\]'
          inline:
            - - '$'
              - '$'
            - - '\('
              - '\)'
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
