theme:
  name: 'material'
  custom_dir: './material'
  feature:
    tabs: true
  language: 'en'
  palette:
    primary: 'Teal'
    accent: 'Cyan'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: "\uE80C"

  #favicon: 'assets/images/favicon.ico'

site_name: "Shashank's Webpage"
site_description: "Webpage of Shashank Obla, PhD Candidate at Carnegie Mellon University"
site_author: 'Shashank Obla'
site_url: 'https://www.andrew.cmu.edu/user/sobla'

copyright: 'Copyright &copy; 2018 - 2021 Shashank Obla'

extra:
# disqus: 'shashankov'
  social:
    - type: 'github-alt'
      link: 'https://github.com/ShashankOV'
    - type: 'facebook'
      link: 'https://www.facebook.com/shashankov'
    - type: 'twitter'
      link: 'https://twitter.com/Shashank_OV'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/shashankov'
    - type: 'instagram'
      link: 'https://instagram.com/shashankov'

google_analytics:
  - 'G-YYCNHNENMQ'
  - 'auto'

markdown_extensions:
  - abbr
  - admonition
  - meta
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home:
    - Brief: 'index.md'
    - Bio: './about/bio.md'
    - Resume: './about/resume.md'
    - Contact: './about/contact.md'
  - Teaching:
    - Teaching Assistantships: 'teaching/index.md'
    - Miscellaneous Resources: 'teaching/misc.md'
    - Ethics: 'teaching/ethics.md'
  - Projects:
    - Abstracts: './projects/index.md'
    - Token System:
      - Getting Started: './projects/token/index.md'
      - Google Forms: './projects/token/forms.md'
      - Configuration: './projects/token/configuration.md'
      - Source: './projects/token/source.md'
