theme:
  name: 'material'
  theme_dir: 'material'
  feature:
    tabs: true
  language: 'en'
  palette:
    primary: 'Teal'
    accent: 'Cyan'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

  #favicon: 'assets/images/favicon.ico'

site_name: "Shashank's Webpage"
site_description: "Webpage of Shashank Obla, Doctoral Student at Carnegie Mellon University"
site_author: 'Shashank Vijayakumar Obla'
site_url: 'https://www.andrew.cmu.edu/user/sobla'

copyright: 'Copyright &copy; 2018 - 2019 Shashank Obla'

extra:
# disqus: 'shashankov'
  social:
    - type: 'github-alt'
      link: 'https://github.com/ShashankOV'
    - type: 'facebook'
      link: 'https://www.facebook.com/shashankov'
    - type: 'twitter'
      link: 'https://twitter.com/Shashank_OV'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/shashankov'
    - type: 'instagram'
      link: 'https://instagram.com/shashankov'

google_analytics:
  - 'UA-119896318-2'
  - 'auto'

markdown_extensions:
  - admonition
  - meta
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: 'index.md'
  - About:
    - Bio: './about/bio.md'
    - CV: './about/CV.md'
    - Contact: './about/contact.md'
  - Teaching: 'teaching.md'
  - Ethics: 'ethics.md'
  - Course Projects:
    - Abstracts: './projects/projects.md'
  - Token System:
    - Getting Started: './projects/token/getting_started.md'
    - Google Forms: './projects/token/forms.md'
    - Configuration: './projects/token/configuration.md'
    - Source: './projects/token/source.md'
